### ISSUE TITLE
Randomize questions before voting. 

### ISSUE THREAD

**Issue by mhoye** [mozilla/mozmoderator#277]
I'd like to change Moderator such that before someone votes, existing questions are shown to them in a random order, without the associated 
vote totals visible.

Once voting has happened, the list can be shown with vote totals in order as usual. I believe this will prevent pile-on questions and make it easier for late entries or otherwise marginal questions to have a better shot at bubbling to the top of the list.

**Comment by felixlawrence** [comment]
> make it easier for late entries

2c: If the list is sorted from most recent question to oldest question, then I think that will be the fairest solution to reduce the bias related to question age. If we assume that the fraction of page views that result in new questions is constant over time, and that the fraction of page views that result in a serious consideration (for voting) of the top n questions is also constant over time, then I think we could actually _prove_ that this is the fairest ordering scheme w.r.t. distributing consideration across the questions. It's also a more ergonomic scheme for people who visit the moderator page on multiple occasions, because the new content for them is all in one place.

**Comment by akatsoulas** [comment]
I opened this https://github.com/mozilla/mozmoderator/pull/279

- It randomizes the order of questions while the event is open (not archived).
- It displays the votes when the event is archived
- When an events gets archived, the questions are ordered based on the vote count
- Admins retain the current functionality. The order is  based on the vote count and can see the votes.

**Comment by The-smooth-operator** [comment]
The PR has been merged and deployed to the stage environment: https://moderator-stage.itsre-apps.mozit.cloud

**Comment by akatsoulas** [comment]
@The-smooth-operator after talking with @mhoye through slack, we can proceed and release this to production.

**Comment by The-smooth-operator** [comment]
@akatsoulas the latest version of Moderator (with the changes requested in this Issue) has been deployed and is now running in production

**Comment by akatsoulas** [comment]
Thanks @The-smooth-operator !
