### ISSUE TITLE
Links to people.mozilla.org are broken

### ISSUE THREAD

**Issue by baumanj** [mozilla/mozmoderator#362]
When a person posts a question (non-anonymously), their avatar is linked to PMO like `https://mozillians.org/u/Full Name`. However, these links are invalid for some (or possibly all) users.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/ME-9)

**Comment by akatsoulas** [comment]
Links have been updated to point to PMO and perform a query based on the username of the user moderator has

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

Clicking on a non-anonymous user avatar redirects the user to the  "https://people.mozilla.org/s/?query={{ profile.username }}&who=staff" ( or {{Given Name Family Name}} for accounts created before https://github.com/mozilla/mozmoderator/pull/458/commits/cee8d067599d52f0292e08750d03a581bfd3cd5a ). The query performed against https://people.mozilla.org successfully returns the correct user.

Moving this ticket inside the `release` column.
